import { Category } from "@/types";

export const categories: Category[] = [
  {
    id: "venture",
    name: "Venture",
    description: "Startup concepts, business models, and entrepreneurial ventures",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of startup or business venture you want.",
      "Create a startup concept for a sustainable fashion marketplace",
      "Propose a disruptive business model for the education industry",
    ],
    systemPrompt: `You are the best venture mind in the world: a legendary serial entrepreneur, venture strategist, and operator who has founded and scaled multiple unicorn companies across categories. You see markets before they are obvious, understand customer pain at ground level, design wedges that compound into dominant companies, and know how real businesses win through distribution, margins, and durable advantage. In this domain, your bar is not "interesting startup idea" - it is "venture-scale inevitability."`,
    evaluationCriteria: [
      "Painkiller problem insight — does it attack a painful, urgent, high-frequency need that incumbents underserve?",
      "Wedge and customer pull — is there a sharp initial customer, use case, and go-to-market path that could win real demand early?",
      "Compounding advantage — does the business build a moat through workflow lock-in, data, network effects, brand, cost, or unique supply?",
      "Business model quality — does it monetize in a way that can scale with strong margins and attractive unit economics?",
      "Market timing and scale — is the timing right, and can the wedge grow into a category-defining company?",
    ],
    ideaSchema: [
      { key: "title", label: "Venture Name", description: "The name of the startup or venture" },
      { key: "summary", label: "One-Line Pitch", description: "A single sentence that makes the company instantly legible" },
      { key: "problem", label: "Painkiller Problem", description: "The painful, urgent problem being solved" },
      { key: "customer", label: "Beachhead Customer", description: "The first customer segment and use case to win" },
      { key: "product", label: "Core Product", description: "What the product does and why it solves the problem better" },
      { key: "whyNow", label: "Why Now", description: "Why this company becomes possible or urgent right now" },
      { key: "goToMarket", label: "Initial Wedge & GTM", description: "How the company lands its first real customers" },
      { key: "moat", label: "Compounding Advantage", description: "Why this gets stronger and harder to copy over time" },
      { key: "businessModel", label: "Business Model", description: "How it makes money with scalable economics" },
      { key: "scaleVision", label: "Category Expansion", description: "How the initial wedge expands into a much bigger company" },
    ],
  },
  {
    id: "frontier",
    name: "Frontier",
    description: "Novel research directions, scientific hypotheses, and academic proposals",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of research direction or hypothesis you want.",
      "Propose a novel approach to carbon capture technology",
      "Design a research study on the cognitive effects of AI-assisted learning",
    ],
    systemPrompt: `You are the best research strategist in the world: a Nobel-caliber interdisciplinary scientist and principal investigator whose work repeatedly opens new fields. You identify important unanswered questions, frame sharp hypotheses, and design decisive experiments that survive skeptical peer review. You think simultaneously like a groundbreaking theorist, a rigorous methodologist, and a top grant reviewer scoring significance, innovation, and feasibility at the highest level.`,
    evaluationCriteria: [
      "Significance of the research question — does it attack an important scientific gap, bottleneck, or unresolved challenge?",
      "Innovation of the core insight — does it introduce a genuinely new concept, method, or explanatory frame?",
      "Rigor and feasibility — is the approach strong enough to produce compelling, reproducible findings within a realistic scope?",
      "Decisiveness and falsifiability — are the hypothesis and tests sharp enough to meaningfully prove or disprove the core claim?",
      "Field-shifting impact — if successful, would this change what the field can explain, measure, or build?",
    ],
    ideaSchema: [
      { key: "title", label: "Research Title", description: "The title of the research proposal" },
      { key: "summary", label: "Abstract", description: "A concise summary of the research direction and claim" },
      { key: "problemGap", label: "Scientific Gap", description: "The unanswered question or bottleneck this addresses" },
      { key: "hypothesis", label: "Core Hypothesis", description: "The central testable claim" },
      { key: "coreInsight", label: "Central Insight", description: "The new idea, mechanism, or conceptual leap" },
      { key: "approach", label: "Research Approach", description: "The overall plan for investigating the idea" },
      { key: "decisiveTest", label: "Decisive Experiment", description: "The key experiment or analysis that would most clearly validate or break the idea" },
      { key: "impact", label: "Transformative Impact", description: "What changes in science or technology if this works" },
    ],
  },
  {
    id: "blueprint",
    name: "Blueprint",
    description: "Inventions, engineering concepts, and innovative technical solutions",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of invention or engineering concept you want.",
      "Propose an invention that makes vertical farming accessible to apartments",
      "Create a concept for a new type of transportation for dense urban areas",
    ],
    systemPrompt: `You are the best inventor-engineer in the world: a legendary builder who combines first-principles physics, industrial design, systems engineering, and product intuition. You repeatedly create inventions that feel obvious in hindsight because they solve painful problems with elegant mechanisms, realistic build paths, and strong human adoption. You think simultaneously about desirability, technical feasibility, manufacturability, safety, and deployment.`,
    evaluationCriteria: [
      "Problem leverage — does it solve a high-value problem where the improvement actually matters?",
      "Mechanism originality — is the core technical principle genuinely new or surprisingly clever?",
      "Technical feasibility — can it be prototyped and built with current or near-future capabilities?",
      "Elegance and robustness — is the solution simple, resilient, and well-matched to the constraint?",
      "Deployability — can it be manufactured, used safely, and adopted in the real world at acceptable cost?",
    ],
    ideaSchema: [
      { key: "title", label: "Invention Name", description: "The name of the invention or concept" },
      { key: "summary", label: "One-Line Function", description: "A single sentence explaining what it does" },
      { key: "problem", label: "Problem", description: "The real-world problem or constraint this addresses" },
      { key: "user", label: "Primary User & Context", description: "Who uses this and in what environment" },
      { key: "mechanism", label: "Core Mechanism", description: "The technical principle that makes it work" },
      { key: "prototype", label: "Prototype Path", description: "How you would build and validate the first working version" },
      { key: "constraints", label: "Safety & Constraints", description: "The main engineering, safety, or regulatory constraints" },
      { key: "deployment", label: "Deployment & Adoption", description: "How this gets manufactured, distributed, and adopted" },
    ],
  },
  {
    id: "story",
    name: "Story",
    description: "Short fiction premises, plot twists, poetry, and narrative concepts",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of story or narrative concept you want.",
      "Write a compelling premise for a sci-fi novel set in 2150",
      "Create an unexpected plot twist for a mystery thriller",
    ],
    systemPrompt: `You are the best storyteller in the world: a master novelist and short-fiction writer with extraordinary command of character, conflict, voice, and narrative design. You create stories readers cannot stop thinking about because every premise contains human urgency, escalating pressure, thematic depth, and an ending that feels both surprising and inevitable. You do not produce generic plots; you generate story engines that can sustain great fiction.`,
    evaluationCriteria: [
      "Character desire and inner tension — is there a protagonist whose need, flaw, or contradiction can drive the story?",
      "Conflict, stakes, and escalation — does the premise naturally generate pressure, consequences, and momentum?",
      "Emotional and thematic resonance — does it promise feeling as well as meaning?",
      "Originality of premise and angle — does it avoid dead tropes and bring a fresh lens or world?",
      "Narrative payoff — does it promise an ending or transformation that feels surprising yet inevitable?",
    ],
    ideaSchema: [
      { key: "title", label: "Title", description: "The title of the story or concept" },
      { key: "summary", label: "Logline", description: "A one-sentence hook that makes the premise instantly clear" },
      { key: "protagonist", label: "Protagonist", description: "Who the story follows and what makes them narratively volatile" },
      { key: "world", label: "Story World", description: "The setting and its most important internal logic" },
      { key: "incitingIncident", label: "Inciting Incident", description: "The event that destabilizes the protagonist's world" },
      { key: "conflictAndStakes", label: "Central Conflict & Stakes", description: "What the protagonist is up against and what they stand to lose" },
      { key: "narrativeArc", label: "Narrative Arc", description: "How the story escalates and transforms over time" },
      { key: "theme", label: "Thematic Core", description: "The deeper human question or idea the story explores" },
    ],
  },
  {
    id: "cinema",
    name: "Cinema",
    description: "Movie pitches, screenplay concepts, and film loglines",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of film concept or screenplay idea you want.",
      "Pitch a psychological thriller set entirely inside a space station",
      "Create a logline for an animated film about sentient ocean currents",
    ],
    systemPrompt: `You are the best film creator in the world: an elite writer-director-producer with blockbuster instincts, auteur taste, and total command of visual storytelling. You think in images, behavior, set pieces, rhythm, tone, and audience tension. You generate movie ideas that are instantly pitchable, emotionally sticky, visually undeniable, and executable as actual films rather than vague prose concepts.`,
    evaluationCriteria: [
      "Cinematic engine — does the concept inherently want to be seen, not merely described?",
      "Character goal, conflict, and stakes — is there a strong dramatic engine inside the movie?",
      "Visual identity and set-piece potential — does it contain images and sequences audiences would remember?",
      "Audience emotion and tonal clarity — is the intended feeling sharp, specific, and sustainable?",
      "Marketable originality and producibility — does it feel fresh while still being makeable and pitchable?",
    ],
    ideaSchema: [
      { key: "title", label: "Film Title", description: "The working title" },
      { key: "summary", label: "Logline", description: "The one-sentence pitch with protagonist, conflict, and stakes" },
      { key: "protagonist", label: "Lead Character", description: "Who the movie follows and why they are compelling onscreen" },
      { key: "world", label: "Cinematic World", description: "The setting, milieu, and visual environment of the film" },
      { key: "centralConflict", label: "Core Conflict", description: "The movie's central dramatic engine" },
      { key: "synopsis", label: "Synopsis", description: "The full story concept including plot progression and tone" },
      { key: "setPieces", label: "Signature Set Pieces", description: "The standout cinematic sequences or images" },
      { key: "toneAudience", label: "Tone & Audience", description: "The emotional promise, tone, and likely audience for the film" },
    ],
  },
  {
    id: "folio",
    name: "Folio",
    description: "Novel premises, nonfiction book concepts, and plot structures",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of book concept you want.",
      "Pitch a nonfiction book about the hidden history of color",
      "Create a premise for a multi-generational family saga spanning 200 years",
    ],
    systemPrompt: `You are the best literary and publishing mind in the world: a rare combination of acclaimed author, editor, and publisher with impeccable taste. You know what makes a book concept durable enough to sustain a full manuscript, distinctive enough to stand out in the market, and meaningful enough to matter culturally. You think in hooks, form, readership, shelf positioning, and the deep structural logic that turns an idea into a real book.`,
    evaluationCriteria: [
      "Hook and necessity — is there a clear reason this book must exist and a sharp way to describe it?",
      "Reader clarity and market gap — is the audience specific, valuable, and underserved by existing books?",
      "Book-length durability — can the concept sustain a full manuscript without padding or repetition?",
      "Structural architecture — is the chosen form the right vessel for the material?",
      "Distinctive voice or authority — does it promise a perspective, sensibility, or authority readers would trust and remember?",
    ],
    ideaSchema: [
      { key: "title", label: "Book Title", description: "The working title" },
      { key: "summary", label: "Elevator Pitch", description: "A one-sentence pitch that captures the book cleanly" },
      { key: "premise", label: "Core Premise", description: "The central concept, argument, or narrative promise of the book" },
      { key: "whyThisBook", label: "Why This Book Must Exist", description: "Why this book matters now and why it earns book-length treatment" },
      { key: "idealReader", label: "Ideal Reader", description: "Who will buy, read, and recommend this book" },
      { key: "marketGap", label: "Market Gap & Shelf Positioning", description: "What gap it fills and how it sits in the literary or commercial landscape" },
      { key: "structure", label: "Book Structure", description: "How the book is organized and why that form works" },
      { key: "voiceAuthority", label: "Voice / Authority", description: "What perspective, authority, or literary sensibility makes this book distinct" },
    ],
  },
  {
    id: "canvas",
    name: "Canvas",
    description: "Visual art directions, sculptural concepts, and game world concepts",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of visual art, game, or music concept you want.",
      "Design an art installation concept that responds to viewers' emotions",
      "Create a video game world inspired by bioluminescent deep-sea creatures",
    ],
    systemPrompt: `You are the best cross-medium creative director in the world: a master of visual art, game worlds, installation design, music-adjacent atmosphere, and interactive experience design. You create projects with unmistakable aesthetic identity, coherent design pillars, and sensory experiences people want to inhabit. You think simultaneously about form, feeling, interaction, world logic, and how every creative choice reinforces the central vision.`,
    evaluationCriteria: [
      "Distinctive aesthetic vision — is the project's look, feel, and atmosphere unmistakable?",
      "Medium fit and interaction logic — does the chosen medium do essential work rather than feeling interchangeable?",
      "Coherence of world and design pillars — do the project's rules, details, and systems reinforce one another?",
      "Sensory and emotional immersion — does it create a felt experience people would want to enter and stay inside?",
      "Memorability and exploration pull — does it make people want to explore, share, replay, or revisit it?",
    ],
    ideaSchema: [
      { key: "title", label: "Project Title", description: "The name of the project" },
      { key: "summary", label: "Vision Statement", description: "A one-sentence encapsulation of the experience" },
      { key: "medium", label: "Medium & Format", description: "The chosen medium and why this idea belongs there" },
      { key: "pillars", label: "Design Pillars", description: "The 3-5 foundational creative principles that govern the project" },
      { key: "worldLogic", label: "World Rules & Logic", description: "The internal rules that make the experience coherent" },
      { key: "sensoryPalette", label: "Sensory Palette", description: "The visual, sonic, tactile, or atmospheric identity of the work" },
      { key: "participantExperience", label: "Participant Experience", description: "What it feels like to move through or interact with the work" },
      { key: "signatureMoment", label: "Signature Moment", description: "The one moment or reveal that people would remember most" },
    ],
  },
  {
    id: "stage",
    name: "Stage",
    description: "Theater productions, musical concepts, and live performance ideas",
    examplePrompts: [
      "No prompt. You are have full and total freedom to propose any kind of stage production or live performance idea you want.",
      "Design a musical concept set in a post-apocalyptic underground city",
      "Create an immersive theater experience based on a classic myth",
    ],
    systemPrompt: `You are the best live-performance creator in the world: an elite playwright, director, and performance-maker who understands exactly what only theater can do. You design productions around presence, audience attention, shared risk, spatial intelligence, and the electric feedback loop between performer and crowd. Your ideas do not merely tell stories onstage; they justify liveness.`,
    evaluationCriteria: [
      "Liveness as the core engine — does the idea depend on shared physical presence and real-time performance?",
      "Actor-audience relationship — does it use the audience relationship deliberately rather than treating spectators as passive viewers?",
      "Emotional and communal impact — would the room feel changed by experiencing this together?",
      "Spatial and staging inventiveness — does the use of space deepen the concept instead of merely housing it?",
      "Produceability — could a real company stage this with a coherent cast, space, and production model?",
    ],
    ideaSchema: [
      { key: "title", label: "Production Title", description: "The name of the show" },
      { key: "summary", label: "One-Line Pitch", description: "A one-sentence hook for the production" },
      { key: "premise", label: "Core Premise", description: "The central dramatic or performance concept" },
      { key: "audienceRelationship", label: "Actor-Audience Relationship", description: "How the production positions, implicates, or involves the audience" },
      { key: "staging", label: "Staging & Space", description: "How the physical environment and movement through space work" },
      { key: "liveMechanics", label: "Live Performance Engine", description: "What can only happen because this is live" },
      { key: "emotionalArc", label: "Emotional Payoff", description: "What the audience should feel over the course of the performance" },
      { key: "productionModel", label: "Production Shape", description: "The cast, music, design, and production shape that make it real" },
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function getAllCategories(): Category[] {
  return categories;
}
